name: Deploy NuxtApp

on:
  push:
    branches: [ "master" ] 

jobs:
  test-lint:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [22.11.0] 
    steps:
    - uses: actions/checkout@v4 
    - name: Install pnpm
      uses: pnpm/action-setup@v4 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'  
    - run: pnpm install --frozen-lockfile
    - run: pnpm run lint
  
  run-tests:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [22.x] 
    steps:
    - uses: actions/checkout@v4 
        
  build-and-deploy:
    needs: [test-lint,run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        env:
          PROJECT_PATH: ${{ vars.FTP_PATH }}   
        with:
          host: ${{ secrets.FTP_SERVER }} 
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          envs: PROJECT_PATH
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            export PNPM_HOME=/root/.local/share/pnpm/
            cd $PROJECT_PATH
            git pull
            pnpm install --frozen-lockfile
            pnpm run build
            pm2 restart Chisel
