name: Deploy NuxtApp

on:
  push:
    branches: [ "master" ] 

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4 
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.FTP_SERVER }} 
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}  
          script: |
            cd /
            ls
