name: Deploy NuxtApp

on:
  push:
    branches: [ "master" ] 

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }} 
        
    - run: npm install
    - run: npm run build --if-present 
    - uses: actions/upload-artifact@v4
      with:
        name: artifacts 
        path: dist/
    - run: ls -a
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4  
        with:
          name: artifacts 
          path: dist
      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir:  ${{ vars.FTP_PATH }}
